---
title: "Lab 04 - Wrangling spatial data"
author: "INSERT TEAM NAME HERE"
date: "INSERT TODAY'S DATE HERE"
output: github_document
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Load data

```{r load-data, message=FALSE}
dn <- read_csv("data/dennys.csv")
lq <- read_csv("data/laquinta.csv")
```

### Specify the haversine function to be used later

```{r}
haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 = long1 * pi / 180
  lat1  = lat1  * pi / 180
  long2 = long2 * pi / 180
  lat2  = lat2  * pi / 180
  
  R = 6371 # Earth mean radius in km
  
  a = sin((lat2 - lat1)/2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1)/2)^2
  d = R * 2 * asin(sqrt(a))
  
  return( round(d,round) ) # distance in km
}
```


(Add code chunks and narrative as needed below.)

### Exercise 1

### Exercise 2

### Exercise 3

### Exercise 4

### Exercise 5

### Exercise 6

### Exercise 7

### Exercise 8

### Exercise 9

### Exercise 10

### Exercise 11

